"""Safe string conversion utilities.

This module provides two functions:
- to_safe_string: convert input to a CSM-safe representation.
- from_safe_string: recover the original string exactly.

The escaping behavior follows CSM keyword-safe conventions:
- Escape CSM keyword characters using ``%HH`` uppercase hex.
- ``%`` is also escaped to keep decoding unambiguous.
"""

from __future__ import annotations

_HEX_DIGITS = set("0123456789ABCDEFabcdef")
_ESCAPE = "%"

# Character-based conservative escaping for CSM keyword safety.
# We escape all characters that appear in documented keyword patterns
# (->, ->|, -@, -&, <-, \r, \n, //, >>, >>>, ;, ,), regardless of context.
_CSM_KEYWORD_CHARS = set("-|@&<>\r\n/;,")
_ESCAPED_CHARS = _CSM_KEYWORD_CHARS | {_ESCAPE}


def to_safe_string(text: str) -> str:
    """Convert string to a reversible CSM-safe string.

    Args:
        text: Any Python string.

    Returns:
        CSM-safe encoded string.
    """
    if not isinstance(text, str):
        raise TypeError("text must be str")

    encoded_parts: list[str] = []
    for ch in text:
        if ch in _ESCAPED_CHARS:
            encoded_parts.append(f"{_ESCAPE}{ch.encode('ascii').hex().upper()}")
        else:
            encoded_parts.append(ch)
    return "".join(encoded_parts)


def from_safe_string(safe_text: str) -> str:
    """Decode safe string back to the original Python string.

    Args:
        safe_text: String generated by ``to_safe_string``.

    Returns:
        Original Python string.

    Raises:
        ValueError: If input is malformed.
    """
    if not isinstance(safe_text, str):
        raise TypeError("safe_text must be str")

    result: list[str] = []
    i = 0
    length = len(safe_text)

    while i < length:
        ch = safe_text[i]
        if ch == _ESCAPE:
            if i + 2 >= length:
                raise ValueError("Malformed safe string: incomplete escape sequence")
            h1, h2 = safe_text[i + 1], safe_text[i + 2]
            if h1 not in _HEX_DIGITS or h2 not in _HEX_DIGITS:
                raise ValueError("Malformed safe string: invalid hex escape")
            result.append(chr(int(h1 + h2, 16)))
            i += 3
            continue

        result.append(ch)
        i += 1

    return "".join(result)
