"""Safe string conversion utilities.

This module provides two functions:
- to_safe_string: convert any Python string to an ASCII-safe representation.
- from_safe_string: recover the original Python string exactly.

Encoding format:
- Input string is first encoded into UTF-8 bytes with ``surrogatepass`` to preserve
  edge cases like lone surrogate code points.
- Bytes mapped to unreserved characters [A-Za-z0-9._-] are emitted directly.
- All other bytes are emitted as ``~HH`` where HH is uppercase hexadecimal.

The output only contains [A-Za-z0-9._-~].
"""

from __future__ import annotations

import string

_HEX_DIGITS = set("0123456789ABCDEFabcdef")
_UNRESERVED = set(string.ascii_letters + string.digits + "._-")
_ESCAPE = "~"


def to_safe_string(text: str) -> str:
    """Convert any Python string to a reversible ASCII-safe string.

    Args:
        text: Any Python string, including empty string, control chars, emoji,
            and lone surrogates.

    Returns:
        ASCII-safe encoded string.
    """
    if not isinstance(text, str):
        raise TypeError("text must be str")

    encoded_parts: list[str] = []
    for byte in text.encode("utf-8", errors="surrogatepass"):
        ch = chr(byte)
        if ch in _UNRESERVED:
            encoded_parts.append(ch)
        else:
            encoded_parts.append(f"{_ESCAPE}{byte:02X}")
    return "".join(encoded_parts)


def from_safe_string(safe_text: str) -> str:
    """Decode safe string back to the original Python string.

    Args:
        safe_text: String generated by ``to_safe_string``.

    Returns:
        Original Python string.

    Raises:
        ValueError: If input is malformed.
    """
    if not isinstance(safe_text, str):
        raise TypeError("safe_text must be str")

    result = bytearray()
    i = 0
    length = len(safe_text)

    while i < length:
        ch = safe_text[i]
        if ch == _ESCAPE:
            if i + 2 >= length:
                raise ValueError("Malformed safe string: incomplete escape sequence")
            h1, h2 = safe_text[i + 1], safe_text[i + 2]
            if h1 not in _HEX_DIGITS or h2 not in _HEX_DIGITS:
                raise ValueError("Malformed safe string: invalid hex escape")
            result.append(int(h1 + h2, 16))
            i += 3
            continue

        if ch not in _UNRESERVED:
            raise ValueError("Malformed safe string: unexpected character")

        result.append(ord(ch))
        i += 1

    return result.decode("utf-8", errors="surrogatepass")
